const movieData = [
  {
    id: "tt6791350",
    title: "Guardians of the Galaxy Vol. 3",
    url: "https://www.rottentomatoes.com/m/guardians_of_the_galaxy_vol_3",
    img: "https://resizing.flixster.com/5seKiRmH981Y2amg0vmHmj5WnXo=/fit-in/180x240/v2/https://resizing.flixster.com/p8g-u3ZgPuxrg4x7aq1tidyffGg=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2FiZDg0OTc0LWVkMTktNDVhYS05ODljLTNkMjYxMjA0OTdjMy5qcGc=",
    year: "2023",
    starring: ["Chris Pratt", "Zoe Saldana", "Dave Bautista", "Karen Gillan"],
    directedBy: ["James Gunn"],
  },
  {
    id: "tt2906216",
    title: "Dungeons & Dragons: Honor Among Thieves",
    url: "https://www.rottentomatoes.com/m/dungeons_and_dragons_honor_among_thieves",
    img: "https://resizing.flixster.com/IwFK1YWt1-pAzhnGdY9KTLLjEQM=/fit-in/180x240/v2/https://resizing.flixster.com/eWLvyboOEGZRS2JiBDZ6eRD4Hps=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzU2MTc5YzE5LTc3YjktNDIyMS05ZWZhLTNlNzBjZmZkM2JlMS5qcGc=",
    year: "2023",
    starring: [
      "Chris Pine",
      "Michelle Rodriguez",
      "Regé-Jean Page",
      "Justice Jesse Smith",
    ],
    directedBy: ["Jonathan M. Goldstein", "John Francis Daley"],
  },
  {
    id: "tt5635026",
    title: "Peter Pan & Wendy",
    url: "https://www.rottentomatoes.com/m/peter_pan_and_wendy",
    img: "https://resizing.flixster.com/yUjbuHdhJI60p_rjKYe-h09vZyM=/fit-in/180x240/v2/https://resizing.flixster.com/VWUm7CchIbz-vWynjdE9q0l3OvU=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2U2OGI1M2FmLWYxZDctNDQxYS04N2ViLThmOTRiNzYwMWUzMC5qcGc=",
    year: "2023",
    starring: [
      "Alexander Molony",
      "Ever Anderson",
      "Jude Law",
      "Alyssa Wapanatâhk",
    ],
    directedBy: ["David Lowery"],
  },
  {
    id: "tt6718170",
    title: "The Super Mario Bros. Movie",
    url: "https://www.rottentomatoes.com/m/the_super_mario_bros_movie",
    img: "https://resizing.flixster.com/-NKi376avuUz6vzaZgW5z4dBkxE=/fit-in/180x240/v2/https://resizing.flixster.com/nQN8KYVFA4fD23Li3TCLwKYz8GA=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2JlYWVjZDdiLTMyYjMtNDgzNy1iN2M0LTgzYWZkODIzMmZmOS5qcGc=",
    year: "2023",
    starring: ["Chris Pratt", "Anya Taylor-Joy", "Charlie Day", "Jack Black"],
    directedBy: ["Aaron Horvath", "Michael Jelenic"],
  },
  {
    id: "tt13345606",
    title: "Evil Dead Rise",
    url: "https://www.rottentomatoes.com/m/evil_dead_rise",
    img: "https://resizing.flixster.com/TWYzWG7xYYms3pGenxWgI3nyErw=/fit-in/180x240/v2/https://resizing.flixster.com/rWoHzijYNZv7RJb5P7BQQoGOo80=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2U2YzliZDFjLWI2NTUtNDFmMi04OTUzLTUwNGFlOTRkOWIyNy5qcGc=",
    year: "2023",
    starring: [
      "Lily Sullivan",
      "Alyssa Sutherland",
      "Morgan Davies",
      "Gabrielle Echols",
    ],
    directedBy: ["Lee Cronin"],
  },
  {
    id: "tt11358390",
    title: "Renfield",
    url: "https://www.rottentomatoes.com/m/renfield",
    img: "https://resizing.flixster.com/mm70RwQfr50zB-xgihilC_1mQOU=/fit-in/180x240/v2/https://resizing.flixster.com/T4HHyueGWhklRu6uZss1jA5PiTY=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzAwODEwNjcxLTFjZWMtNDJlNC1hOGI2LWIwNzlkZjg3MjFlNS5qcGc=",
    year: "2023",
    starring: ["Nicolas Cage", "Nicholas Hoult", "Awkwafina", "Ben Schwartz"],
    directedBy: ["Chris McKay"],
  },
  {
    id: "tt15326988",
    title: "Ghosted",
    url: "https://www.rottentomatoes.com/m/ghosted_2023",
    img: "https://resizing.flixster.com/F_KYTBylpfRC_qfGgLIeSDCfyi0=/fit-in/180x240/v2/https://resizing.flixster.com/b-IiMmd59d7GxQeGfXt2_0GIaD0=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzg0ZTc3NWY1LTFmNWMtNGZkNi1hYjIwLWIzMjkyNDYwNDczNi5wbmc=",
    year: "2023",
    starring: ["Chris Evans", "Ana de Armas", "Adrien Brody", "Mike Moh"],
    directedBy: ["Dexter Fletcher"],
  },
  {
    id: "tt10366206",
    title: "John Wick: Chapter 4",
    url: "https://www.rottentomatoes.com/m/john_wick_chapter_4",
    img: "https://resizing.flixster.com/AplxvuaxmELPdwmen0mu3uivAlA=/fit-in/180x240/v2/https://resizing.flixster.com/ayiSi8HrUS3_i-Jkru1P2oMM58Q=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzhiODAwYWIyLTM1MmItNGI1ZS1iOWQzLTdjZjAzMzI1MDc2Yy5qcGc=",
    year: "2023",
    starring: [
      "Keanu Reeves",
      "Donnie Yen Ji-Dan",
      "Bill Skarsgård",
      "Laurence Fishburne",
    ],
    directedBy: ["Chad Stahelski"],
  },
  {
    id: "tt16428256",
    title: "Suzume",
    url: "https://www.rottentomatoes.com/m/suzume",
    img: "https://resizing.flixster.com/hVnX-9A1RhFcU587nxiI6R5-bs4=/fit-in/180x240/v2/https://resizing.flixster.com/zg3xSM8uDH5CXhrMDpZ-p4qhpp8=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzI3OGExOWVjLTIwNGEtNGRhNS1hMzIxLTE5OGFhYWNlOWRhOS5wbmc=",
    year: "2022",
    starring: [
      "Nanoka Hara",
      "Hokuto Matsumura",
      "Eri Fukatsu",
      "Hakuo Matsumoto II",
    ],
    directedBy: ["Makoto Shinkai"],
  },
  {
    id: "tt7405458",
    title: "A Man Called Otto",
    url: "https://www.rottentomatoes.com/m/a_man_called_otto",
    img: "https://resizing.flixster.com/vVUWQMLIueGcmqsLjpPutdey_yI=/fit-in/180x240/v2/https://resizing.flixster.com/l3hMOt6cWOpnE-s2f9ryvvFRwdM=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzQxYjJlNGIwLWE1YWMtNDU0NC05NDc3LTVkMTUwYWMyZGIyNy5qcGc=",
    year: "2022",
    starring: ["Tom Hanks", "Mack Bayda", "Mariana Treviño", "Rachel Keller"],
    directedBy: ["Marc Forster"],
  },
];

export default movieData;
