const movieData = [
  {
    id: "tt6791350",
    title: "Guardians of the Galaxy Vol. 3",
    url: "https://www.rottentomatoes.com/m/guardians_of_the_galaxy_vol_3",
    img: "https://resizing.flixster.com/5seKiRmH981Y2amg0vmHmj5WnXo=/fit-in/180x240/v2/https://resizing.flixster.com/p8g-u3ZgPuxrg4x7aq1tidyffGg=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2FiZDg0OTc0LWVkMTktNDVhYS05ODljLTNkMjYxMjA0OTdjMy5qcGc=",
    year: "2023",
    starring: ["Chris Pratt", "Zoe Saldana", "Dave Bautista", "Karen Gillan"],
    directedBy: ["James Gunn"],
  },
  {
    id: "tt2906216",
    title: "Dungeons & Dragons: Honor Among Thieves",
    url: "https://www.rottentomatoes.com/m/dungeons_and_dragons_honor_among_thieves",
    img: "https://resizing.flixster.com/IwFK1YWt1-pAzhnGdY9KTLLjEQM=/fit-in/180x240/v2/https://resizing.flixster.com/eWLvyboOEGZRS2JiBDZ6eRD4Hps=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzU2MTc5YzE5LTc3YjktNDIyMS05ZWZhLTNlNzBjZmZkM2JlMS5qcGc=",
    year: "2023",
    starring: [
      "Chris Pine",
      "Michelle Rodriguez",
      "Regé-Jean Page",
      "Justice Jesse Smith",
    ],
    directedBy: ["Jonathan M. Goldstein", "John Francis Daley"],
  },
  {
    id: "tt5635026",
    title: "Peter Pan & Wendy",
    url: "https://www.rottentomatoes.com/m/peter_pan_and_wendy",
    img: "https://resizing.flixster.com/yUjbuHdhJI60p_rjKYe-h09vZyM=/fit-in/180x240/v2/https://resizing.flixster.com/VWUm7CchIbz-vWynjdE9q0l3OvU=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2U2OGI1M2FmLWYxZDctNDQxYS04N2ViLThmOTRiNzYwMWUzMC5qcGc=",
    year: "2023",
    starring: [
      "Alexander Molony",
      "Ever Anderson",
      "Jude Law",
      "Alyssa Wapanatâhk",
    ],
    directedBy: ["David Lowery"],
  },
  {
    id: "tt6718170",
    title: "The Super Mario Bros. Movie",
    url: "https://www.rottentomatoes.com/m/the_super_mario_bros_movie",
    img: "https://resizing.flixster.com/-NKi376avuUz6vzaZgW5z4dBkxE=/fit-in/180x240/v2/https://resizing.flixster.com/nQN8KYVFA4fD23Li3TCLwKYz8GA=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2JlYWVjZDdiLTMyYjMtNDgzNy1iN2M0LTgzYWZkODIzMmZmOS5qcGc=",
    year: "2023",
    starring: ["Chris Pratt", "Anya Taylor-Joy", "Charlie Day", "Jack Black"],
    directedBy: ["Aaron Horvath", "Michael Jelenic"],
  },
  {
    id: "tt9185206",
    title: "Are You There God? It's Me, Margaret.",
    url: "https://www.rottentomatoes.com/m/are_you_there_god_its_me_margaret",
    img: "https://resizing.flixster.com/wx23zKc13hf4rQKR9gdL2T8LA5k=/fit-in/180x240/v2/https://resizing.flixster.com/iOBz-fQyXc6eRWGuSH5d42dsHT0=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzA4YzRmNjcwLTUxOWUtNDJkZi05NmYyLTVjN2MyNDdjNzdiNy5qcGc=",
    year: "2023",
    starring: [
      "Rachel McAdams",
      "Abby Ryder Fortson",
      "Elle Graham",
      "Ben Safdie",
    ],
    directedBy: ["Kelly Fremon Craig"],
  },
  {
    id: "tt13345606",
    title: "Evil Dead Rise",
    url: "https://www.rottentomatoes.com/m/evil_dead_rise",
    img: "https://resizing.flixster.com/TWYzWG7xYYms3pGenxWgI3nyErw=/fit-in/180x240/v2/https://resizing.flixster.com/rWoHzijYNZv7RJb5P7BQQoGOo80=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2U2YzliZDFjLWI2NTUtNDFmMi04OTUzLTUwNGFlOTRkOWIyNy5qcGc=",
    year: "2023",
    starring: [
      "Lily Sullivan",
      "Alyssa Sutherland",
      "Morgan Davies",
      "Gabrielle Echols",
    ],
    directedBy: ["Lee Cronin"],
  },
  {
    id: "tt11358390",
    title: "Renfield",
    url: "https://www.rottentomatoes.com/m/renfield",
    img: "https://resizing.flixster.com/mm70RwQfr50zB-xgihilC_1mQOU=/fit-in/180x240/v2/https://resizing.flixster.com/T4HHyueGWhklRu6uZss1jA5PiTY=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzAwODEwNjcxLTFjZWMtNDJlNC1hOGI2LWIwNzlkZjg3MjFlNS5qcGc=",
    year: "2023",
    starring: ["Nicolas Cage", "Nicholas Hoult", "Awkwafina", "Ben Schwartz"],
    directedBy: ["Chris McKay"],
  },
  {
    id: "tt14846026",
    title: "Sisu",
    url: "https://www.rottentomatoes.com/m/sisu_2022",
    img: "https://resizing.flixster.com/YVJ8IbGr48YrXZwFhXl9tgvZUpk=/fit-in/180x240/v2/https://resizing.flixster.com/LUMlPb01hdWx1gtuOyg1fs2kMyI=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2M0NjVmNThhLTI3MDctNDkwOS1iZDA4LTE1YmQwODE3Yzc1Ni5wbmc=",
    year: "2022",
    starring: [
      "Jorma Tommila",
      "Aksel Hennie",
      "Jack Doolan",
      "Mimosa Willamo",
    ],
    directedBy: ["Jalmari Helander"],
  },
  {
    id: "tt10276482",
    title: "Love Again",
    url: "https://www.rottentomatoes.com/m/love_again_2023",
    img: "https://resizing.flixster.com/rAhrlCahH06bq3-NCh3bXSCqJUc=/fit-in/180x240/v2/https://resizing.flixster.com/alOakbJDC5a_0QVvjWpTc2KZanQ=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzI4OWUyNDQ1LTE4MWQtNGFlZC1iM2Q5LWYyMzcwZDBmOTlhOC5qcGc=",
    year: "2023",
    starring: [
      "Priyanka Chopra Jonas",
      "Sam Heughan",
      "Céline Dion",
      "Russell Tovey",
    ],
    directedBy: ["James C. Strouse"],
  },
  {
    id: "tt2015381",
    title: "Guardians of the Galaxy",
    url: "https://www.rottentomatoes.com/m/guardians_of_the_galaxy",
    img: "https://resizing.flixster.com/7H4GbcaDT6cXBE83fuTtMKSpBI0=/fit-in/180x240/v2/https://resizing.flixster.com/SneFHH-BDOhBkh7h1A-aNwcrxLM=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2U3YTY2YTQzLTU5NDgtNDNiMC04ZTI1LTFiZDYyMTMxMjc5MC5qcGc=",
    year: "2014",
    starring: ["Chris Pratt", "Zoe Saldana", "Dave Bautista", "Vin Diesel"],
    directedBy: ["James Gunn"],
  },
  {
    id: "tt20859464",
    title: "The Artifice Girl",
    url: "https://www.rottentomatoes.com/m/the_artifice_girl",
    img: "https://resizing.flixster.com/bDVwK7DqQVdvMd7kvJR0IxL0hWI=/fit-in/180x240/v2/https://resizing.flixster.com/LNpanjbzPIvazihVyRU3uwEYccc=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2QyZjI4Zjc5LTg2NGQtNGZiZS05MmUxLTI0ZGMwODI3M2M0OS5qcGc=",
    year: "2022",
    starring: [
      "Tatum Matthews",
      "David Girard",
      "Sinda Nichols",
      "Franklin Ritch",
    ],
    directedBy: ["Franklin Ritch"],
  },
  {
    id: "tt13521006",
    title: "Beau Is Afraid",
    url: "https://www.rottentomatoes.com/m/beau_is_afraid",
    img: "https://resizing.flixster.com/WyAf-x6RifmVU8SaqqqYHpW5N8w=/fit-in/180x240/v2/https://resizing.flixster.com/QdFUG32U5gyx2uVinx5asNZTgyQ=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzczMjQ1ZWQ3LTZhOGMtNDIyYi05NGU5LTk3ZGYyMTYzN2IxNS5qcGc=",
    year: "2023",
    starring: ["Joaquin Phoenix", "Nathan Lane", "Amy Ryan", "Parker Posey"],
    directedBy: ["Ari Aster"],
  },
  {
    id: "tt7405458",
    title: "A Man Called Otto",
    url: "https://www.rottentomatoes.com/m/a_man_called_otto",
    img: "https://resizing.flixster.com/vVUWQMLIueGcmqsLjpPutdey_yI=/fit-in/180x240/v2/https://resizing.flixster.com/l3hMOt6cWOpnE-s2f9ryvvFRwdM=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzQxYjJlNGIwLWE1YWMtNDU0NC05NDc3LTVkMTUwYWMyZGIyNy5qcGc=",
    year: "2022",
    starring: ["Tom Hanks", "Mack Bayda", "Mariana Treviño", "Rachel Keller"],
    directedBy: ["Marc Forster"],
  },
  {
    id: "tt4873118",
    title: "Guy Ritchie's The Covenant",
    url: "https://www.rottentomatoes.com/m/guy_ritchies_the_covenant",
    img: "https://resizing.flixster.com/ofKFW_J0N4i7oo_Zg4XdBQ_uzuA=/fit-in/180x240/v2/https://flxt.tmsimg.com/assets/p23680547_p_v8_aa.jpg",
    year: "2023",
    starring: [
      "Jake Gyllenhaal",
      "Dar Salim",
      "Antony Starr",
      "Alexander Ludwig",
    ],
    directedBy: ["Guy Ritchie"],
  },
  {
    id: "tt15326988",
    title: "Ghosted",
    url: "https://www.rottentomatoes.com/m/ghosted_2023",
    img: "https://resizing.flixster.com/F_KYTBylpfRC_qfGgLIeSDCfyi0=/fit-in/180x240/v2/https://resizing.flixster.com/b-IiMmd59d7GxQeGfXt2_0GIaD0=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzg0ZTc3NWY1LTFmNWMtNGZkNi1hYjIwLWIzMjkyNDYwNDczNi5wbmc=",
    year: "2023",
    starring: ["Chris Evans", "Ana de Armas", "Adrien Brody", "Mike Moh"],
    directedBy: ["Dexter Fletcher"],
  },
  {
    id: "tt14537248",
    title: "Nefarious",
    url: "https://www.rottentomatoes.com/m/nefarious_2023",
    img: "https://resizing.flixster.com/6gGCM-Sh-mUSLoirOlKs-RplQlY=/fit-in/180x240/v2/https://resizing.flixster.com/CoV9h8uAjRfrx5fFGDo-BSKvbWk=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzIxY2NmYmU1LWJkZjUtNDE0MC1iNTlhLTY3OTFmZDRlMmE0NC5qcGc=",
    year: "2023",
    starring: [
      "Sean Patrick Flanery",
      "Jordan Belfi",
      "Tom Ohmer",
      "James Healy Jr.",
    ],
    directedBy: ["Cary Solomon", "Chuck Konzelman"],
  },
  {
    id: "tt16419074",
    title: "Air",
    url: "https://www.rottentomatoes.com/m/air_2023",
    img: "https://resizing.flixster.com/ST_zNMZFnvhHGcCykyNBe18iF-A=/fit-in/180x240/v2/https://resizing.flixster.com/YCmO8jyzF8PEJ5djT_x4TiRAw7Y=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzg0MjcwZGUyLTE4NzctNDgyMi05ZmI0LWM4OWJkZjgxMDMyMi5qcGc=",
    year: "2023",
    starring: ["Matt Damon", "Ben Affleck", "Jason Bateman", "Viola Davis"],
    directedBy: ["Ben Affleck"],
  },
  {
    id: "tt10366206",
    title: "John Wick: Chapter 4",
    url: "https://www.rottentomatoes.com/m/john_wick_chapter_4",
    img: "https://resizing.flixster.com/AplxvuaxmELPdwmen0mu3uivAlA=/fit-in/180x240/v2/https://resizing.flixster.com/ayiSi8HrUS3_i-Jkru1P2oMM58Q=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzhiODAwYWIyLTM1MmItNGI1ZS1iOWQzLTdjZjAzMzI1MDc2Yy5qcGc=",
    year: "2023",
    starring: [
      "Keanu Reeves",
      "Donnie Yen Ji-Dan",
      "Bill Skarsgård",
      "Laurence Fishburne",
    ],
    directedBy: ["Chad Stahelski"],
  },
  {
    id: "tt9130508",
    title: "Cherry",
    url: "https://www.rottentomatoes.com/m/cherry_2022",
    img: "https://resizing.flixster.com/cz05ACPHmwdjqknSy_l6k6vc_-g=/fit-in/180x240/v2/https://resizing.flixster.com/FNT1CJCg1rLwF3_pM_x98BAxfdY=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2QzZTQ2OGYyLTBjYWUtNDc5Ny05OWFlLTczZDQyMzkzNjgzNS5qcGc=",
    year: "2022",
    starring: [
      "Alex Trewhitt",
      "Hannah Alline",
      "Angela Nicholas",
      "Joe Sachem",
    ],
    directedBy: ["Sophie Galibert"],
  },
  {
    id: "tt12427158",
    title: "A Thousand and One",
    url: "https://www.rottentomatoes.com/m/a_thousand_and_one",
    img: "https://resizing.flixster.com/BqfhTsztSgjQLQyu_dyJRPfqt8o=/fit-in/180x240/v2/https://resizing.flixster.com/KJx1vlpDupJIO72dtK0uAYglZok=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzkyNzI4MTJhLTU5Y2MtNDFiZi1iZTVmLTUyYWRkNmQwZDgxYS5qcGc=",
    year: "2023",
    starring: [
      "Teyana Taylor",
      "Aaron Kingsley Adetola",
      "Aven Courtney",
      "Josiah Cross",
    ],
    directedBy: ["A.V. Rockwell"],
  },
  {
    id: "tt12226632",
    title:
      "Big George Foreman: The Miraculous Story of the Once and Future Heavyweight Champion of the World",
    url: "https://www.rottentomatoes.com/m/big_george_foreman_the_miraculous_story_of_the_once_and_future_heavyweight_champion_of_the_world",
    img: "https://resizing.flixster.com/bRuwb_uTY3-qIP3fdLY-vYOMMew=/fit-in/180x240/v2/https://resizing.flixster.com/z6oKt8t0EjwC1NGYKS7PzPb2U68=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2E4ZTNlNDRmLWQ5ODQtNDc0Yy1hY2NmLWI3Yzc5OGRiZThiZi5wbmc=",
    year: "2023",
    starring: [
      "Khris Davis",
      "Forest Whitaker",
      "Jasmine Mathews",
      "Sullivan Jones",
    ],
    directedBy: ["George Tillman Jr."],
  },
  {
    id: "tt17663992",
    title: "Scream VI",
    url: "https://www.rottentomatoes.com/m/scream_vi",
    img: "https://resizing.flixster.com/0djqHUvHt2KPc6yCTgFjvD-YBA4=/fit-in/180x240/v2/https://resizing.flixster.com/dbokT9ziX9XrMs2Ims1OnyLJYmI=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzk3ZmU4OTRlLWM5YTAtNDU3Ni04ODNiLWUxZDE1ZmY1MWQ3Yi5qcGc=",
    year: "2023",
    starring: [
      "Melissa Barrera",
      "Jenna Ortega",
      "Courteney Cox",
      "Jasmin Savoy Brown",
    ],
    directedBy: ["Matt Bettinelli-Olpin", "Tyler Gillett"],
  },
  {
    id: "tt3892172",
    title: "Leave No Trace",
    url: "https://www.rottentomatoes.com/m/leave_no_trace",
    img: "https://resizing.flixster.com/_W-aPvF4lhD6wPbg_lnsQCmPJf0=/fit-in/180x240/v2/https://resizing.flixster.com/qF1V53LvHZfdeJGYQt0E8jsTVg0=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzIyMWNhY2M3LWZjMTItNDdmOS1iYjZjLTM2NmVlNzA4NDc5NC53ZWJw",
    year: "2018",
    starring: ["Ben Foster", "Thomasin McKenzie", "Jeff Kober", "Dale Dickey"],
    directedBy: ["Debra Granik"],
  },
  {
    id: "tt17219484",
    title: "Clock",
    url: "https://www.rottentomatoes.com/m/clock_2023",
    img: "https://resizing.flixster.com/OHkXrX8Z9IWnYg3ql4gpLfcBmuM=/fit-in/180x240/v2/https://resizing.flixster.com/Yr1tMeVwrcXMmyOod8cPnMls32c=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzMzOWE2OWViLThkOTQtNDZjYS1iNTRkLTBkNGViOTRhNGNmMy5qcGc=",
    year: "2023",
    starring: ["Dianna Agron", "Melora Hardin", "Jay Ali", "Saul Rubinek"],
    directedBy: ["Alexis Jacknow"],
  },
  {
    id: "tt16428256",
    title: "Suzume",
    url: "https://www.rottentomatoes.com/m/suzume",
    img: "https://resizing.flixster.com/hVnX-9A1RhFcU587nxiI6R5-bs4=/fit-in/180x240/v2/https://resizing.flixster.com/zg3xSM8uDH5CXhrMDpZ-p4qhpp8=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzI3OGExOWVjLTIwNGEtNGRhNS1hMzIxLTE5OGFhYWNlOWRhOS5wbmc=",
    year: "2022",
    starring: [
      "Nanoka Hara",
      "Hokuto Matsumura",
      "Eri Fukatsu",
      "Hakuo Matsumoto II",
    ],
    directedBy: ["Makoto Shinkai"],
  },
  {
    id: "tt13430858",
    title: "What's Love Got to Do with It?",
    url: "https://www.rottentomatoes.com/m/whats_love_got_to_do_with_it_2023",
    img: "https://resizing.flixster.com/A0gsCl6n_u39vT3PkYoNm7CkvNs=/fit-in/180x240/v2/https://resizing.flixster.com/TfRd-g_MoJhaaKsguoYi5B9axqA=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzEyMmNkN2ZjLTZjYjQtNDFhNy05YTU4LTc3NTkzZWYzYTFkMS5qcGc=",
    year: "2022",
    starring: ["Lily James", "Shazad Latif", "Emma Thompson", "Shabana Azmi"],
    directedBy: ["Shekhar Kapur"],
  },
  {
    id: "tt14668044",
    title: "Discontinued",
    url: "https://www.rottentomatoes.com/m/discontinued",
    img: "https://resizing.flixster.com/lxkgf8hG2Od8jkIJ3fmxjrDYswU=/fit-in/180x240/v2/https://resizing.flixster.com/oMsGfGM4ZwninOuyG8oNqjBXRPw=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2FjOGQ5YjA5LWU2MjItNGRjMi1hOTg4LWM0MzViMDM3MmY4YS5qcGc=",
    year: "2022",
    starring: [
      "Ashley Hutchinson",
      "Langston Fishburne",
      "Robert Picardo",
      "Charlie Talbert",
    ],
    directedBy: ["Trevor Peckham"],
  },
  {
    id: "tt5688068",
    title: "Above Suspicion",
    url: "https://www.rottentomatoes.com/m/above_suspicion_2021",
    img: "https://resizing.flixster.com/COHKBKZILuvRZPS28RTlYkorRy0=/fit-in/180x240/v2/https://resizing.flixster.com/sBuSy1kSk7JlkyEZK8IE3U5tFPA=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2FmZWJkZjg1LThiNTMtNDQyYy1hMGY1LWY0MmQ1NzdjNTI5Yy5qcGc=",
    year: "2019",
    starring: [
      "Emilia Clarke",
      "Thora Birch",
      "Jack Huston",
      "Johnny Knoxville",
    ],
    directedBy: ["Phillip Noyce"],
  },
  {
    id: "tt1160419",
    title: "Dune",
    url: "https://www.rottentomatoes.com/m/dune_2021",
    img: "https://resizing.flixster.com/vAMXFndR8C7FvLvRw7d7OaZumQ8=/fit-in/180x240/v2/https://resizing.flixster.com/gcRn4_emLo1Iz5ndbvUOKDYq35c=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzdhYTI2NDJkLTU5YTYtNDNkOS05ZWQxLWZiNjFlOTZmYjZlZS5qcGc=",
    year: "2021",
    starring: [
      "Timothée Chalamet",
      "Rebecca Ferguson",
      "Oscar Isaac",
      "Josh Brolin",
    ],
    directedBy: ["Denis Villeneuve"],
  },
  {
    id: "tt5215534",
    title: "65",
    url: "https://www.rottentomatoes.com/m/65",
    img: "https://resizing.flixster.com/OOgo6KlgcJ412GSkVhh85LXBEi0=/fit-in/180x240/v2/https://resizing.flixster.com/B3PKF59iChbIK81k7aF0tgkY8_8=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2E4Yzc2ZmE2LWM5MGEtNDdkNS05MWY1LWY2ZDU0N2IwMjdlZi5qcGc=",
    year: "2023",
    starring: ["Adam Driver", "Ariana Greenblatt", "Chloe Coleman"],
    directedBy: ["Scott Beck", "Bryan Woods"],
  },
];

export default movieData;
